# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160305_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/profile_pic/default_user.png', upload_to='profile_pic/'),
        ),
    ]
