# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pic/user.png', upload_to='profile_pic/'),
        ),
    ]
