# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160407_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profile_pic',
        ),
    ]
